import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import QueryProvider from "@/provider/QueryProvider";
import StoreProvider from "@/provider/StoreProvider";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <StoreProvider>
          <QueryProvider>
            <Header />
            {children}
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
