"""Added foreign keys to Order

Revision ID: 16644a90ed8e
Revises: 2faf8de5b67f
Create Date: 2025-03-31 14:25:58.421875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16644a90ed8e'
down_revision = '2faf8de5b67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_pid_fkey', type_='foreignkey')
        batch_op.drop_column('pid')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('orders_pid_fkey', 'product', ['pid'], ['pid'])

    # ### end Alembic commands ###
