"""Create orders table

Revision ID: 61c5abd1b49f
Revises: 44ac49d1d9df
Create Date: 2025-03-31 14:35:30.725428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c5abd1b49f'
down_revision = '44ac49d1d9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('oiid', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('pid', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oid'], ['orders.oid'], ),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], ),
    sa.PrimaryKeyConstraint('oiid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    # ### end Alembic commands ###
