"""Create orders table

Revision ID: 7a33d1529f2b
Revises: 61c5abd1b49f
Create Date: 2025-03-31 14:41:48.258344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a33d1529f2b'
down_revision = '61c5abd1b49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'product', ['pid'], ['pid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('pid')

    op.create_table('order_item',
    sa.Column('oiid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('oid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('pid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['oid'], ['orders.oid'], name='order_item_oid_fkey'),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], name='order_item_pid_fkey'),
    sa.PrimaryKeyConstraint('oiid', name='order_item_pkey')
    )
    # ### end Alembic commands ###
